/**
 * Game catalog seeds. Idempotent: re-running upserts on the `slug` unique index.
 *
 * Source: PRODUCT_VISION.md §8 + DOMAIN_MODEL.md §5.1. Mirrors
 * `packages/mock-data/src/games.ts` so frontend code and DB rows agree on slug.
 */

import type { GameInsert } from '../schema/games';

export const GAME_SEEDS: GameInsert[] = [
  {
    slug: 'cs2',
    name: 'Counter-Strike 2',
    publisher: 'Valve',
    category: 'fps',
    teamSizeDefault: 5,
    teamSizeMin: 5,
    teamSizeMax: 5,
    defaultMatchFormat: 'bo3',
    defaultDurationMinutes: 90,
    supportsInGameId: true,
    inGameIdLabel: 'Steam ID',
    isActive: true,
  },
  {
    slug: 'valorant',
    name: 'VALORANT',
    publisher: 'Riot Games',
    category: 'fps',
    teamSizeDefault: 5,
    teamSizeMin: 5,
    teamSizeMax: 5,
    defaultMatchFormat: 'bo3',
    defaultDurationMinutes: 90,
    supportsInGameId: true,
    inGameIdLabel: 'Riot ID',
    isActive: true,
  },
  {
    slug: 'lol',
    name: 'League of Legends',
    publisher: 'Riot Games',
    category: 'moba',
    teamSizeDefault: 5,
    teamSizeMin: 5,
    teamSizeMax: 5,
    defaultMatchFormat: 'bo3',
    defaultDurationMinutes: 120,
    supportsInGameId: true,
    inGameIdLabel: 'Riot ID',
    isActive: true,
  },
  {
    slug: 'eafc',
    name: 'EA FC 25',
    publisher: 'EA Sports',
    category: 'sports',
    teamSizeDefault: 1,
    teamSizeMin: 1,
    teamSizeMax: 2,
    defaultMatchFormat: 'bo3',
    defaultDurationMinutes: 30,
    supportsInGameId: true,
    inGameIdLabel: 'EA ID',
    isActive: true,
  },
  {
    slug: 'codm',
    name: 'Call of Duty: Mobile',
    publisher: 'Activision',
    category: 'fps',
    teamSizeDefault: 5,
    teamSizeMin: 5,
    teamSizeMax: 5,
    defaultMatchFormat: 'bo3',
    defaultDurationMinutes: 60,
    supportsInGameId: true,
    inGameIdLabel: 'Activision ID',
    isActive: true,
  },
  {
    slug: 'tekken8',
    name: 'Tekken 8',
    publisher: 'Bandai Namco',
    category: 'fighting',
    teamSizeDefault: 1,
    teamSizeMin: 1,
    teamSizeMax: 1,
    defaultMatchFormat: 'bo5',
    defaultDurationMinutes: 30,
    supportsInGameId: true,
    inGameIdLabel: 'Tekken ID',
    isActive: true,
  },
];
