/**
 * Venue seeds — mirrors `packages/mock-data/src/venues.ts`. 5 KW + 1 KSA venues.
 */

import type { VenueInsert } from '../schema/venues';

export type VenueSeed = Omit<
  VenueInsert,
  'id' | 'createdAt' | 'updatedAt' | 'deletedAt' | 'organizationId'
> & {
  /** Reference to organizations.slug — resolved at seed time to organization_id. */
  organizationSlug?: string;
  /** Game slugs supported at this venue. */
  gameSlugs: string[];
};

export const VENUE_SEEDS: VenueSeed[] = [
  {
    slug: 'gg-arena-salmiya',
    name: 'GG Arena',
    organizationSlug: 'gg-arena-org',
    countryCode: 'KW',
    city: 'Salmiya',
    address: 'Salem Al-Mubarak St, Salmiya',
    latitude: 29.3402,
    longitude: 48.0775,
    coverImageUrl: null,
    totalSeats: 30,
    pcSeats: 20,
    consoleSeats: 8,
    mobileSeats: 2,
    privateRoomsCount: 1,
    verificationStatus: 'verified',
    verifiedAt: new Date('2026-04-25T10:00:00Z'),
    isActive: true,
    defaultHourlyRateKwd: 6,
    cancellationPolicy: 'moderate',
    cancellationWindowHours: 24,
    rating: 4.8,
    gameSlugs: ['valorant', 'eafc', 'tekken8'],
  },
  {
    slug: 'pixel-house-hawally',
    name: 'Pixel House',
    countryCode: 'KW',
    city: 'Hawally',
    address: 'Tunis St, Hawally',
    latitude: 29.3331,
    longitude: 48.0301,
    totalSeats: 18,
    pcSeats: 8,
    consoleSeats: 8,
    mobileSeats: 2,
    privateRoomsCount: 0,
    verificationStatus: 'verified',
    verifiedAt: new Date('2026-04-26T10:00:00Z'),
    isActive: true,
    defaultHourlyRateKwd: 5,
    cancellationPolicy: 'flexible',
    cancellationWindowHours: 12,
    rating: null,
    gameSlugs: ['codm', 'tekken8'],
  },
  {
    slug: 'arc-esports-kuwait-city',
    name: 'ARC Esports',
    countryCode: 'KW',
    city: 'Kuwait City',
    address: 'Block 5, Sharq, Kuwait City',
    latitude: 29.3771,
    longitude: 47.9762,
    totalSeats: 40,
    pcSeats: 30,
    consoleSeats: 6,
    mobileSeats: 4,
    privateRoomsCount: 2,
    verificationStatus: 'verified',
    verifiedAt: new Date('2026-04-27T10:00:00Z'),
    isActive: true,
    defaultHourlyRateKwd: 7,
    cancellationPolicy: 'strict',
    cancellationWindowHours: 48,
    rating: null,
    gameSlugs: ['valorant', 'cs2', 'lol'],
  },
  {
    slug: 'qmark-farwaniya',
    name: 'Q-Mark Lounge',
    countryCode: 'KW',
    city: 'Farwaniya',
    latitude: 29.2773,
    longitude: 47.9583,
    totalSeats: 22,
    pcSeats: 8,
    consoleSeats: 12,
    mobileSeats: 2,
    privateRoomsCount: 0,
    verificationStatus: 'verified',
    verifiedAt: new Date('2026-04-28T10:00:00Z'),
    isActive: true,
    defaultHourlyRateKwd: 4,
    cancellationPolicy: 'flexible',
    cancellationWindowHours: 12,
    rating: null,
    gameSlugs: ['eafc', 'codm'],
  },
  {
    slug: 'dxe-fuel-riyadh',
    name: 'DXE Fuel',
    organizationSlug: 'dxe-fuel-org',
    countryCode: 'KSA',
    city: 'Riyadh',
    address: 'Olaya St, Riyadh',
    latitude: 24.7136,
    longitude: 46.6753,
    totalSeats: 50,
    pcSeats: 20,
    consoleSeats: 25,
    mobileSeats: 5,
    privateRoomsCount: 3,
    verificationStatus: 'verified',
    verifiedAt: new Date('2026-04-22T10:00:00Z'),
    isActive: true,
    defaultHourlyRateKwd: 8,
    cancellationPolicy: 'moderate',
    cancellationWindowHours: 24,
    rating: null,
    gameSlugs: ['eafc', 'tekken8'],
  },
];
